version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    # Aquí definimos grupos separados bajo el mismo ecosistema
    groups:
      production-updates:
        dependency-type: "production"
        update-types: ["minor", "patch"]

      development-updates:
        dependency-type: "development"
        # Esto agrupa todo lo de desarrollo
        applies-to: "version-updates"
